Models/Request.cs
using System.Linq;
using System;
using System.ComponentModel.DataAnnotations;

namespace dz.SoftwareRequest.Models
{
    public class Request 
    {
        public Request(){}
        public int Id { get; set; }
        public string DocNo { get; set; }
        public ActionRole RequestBy { get; set; }
        public ActionRole ApproveBy { get; set;}
        public string Title { get; set; }           
        [MaxLength(5000)]
        public string Description { get; set; }
        public string MeetingDate {get;set;}
        public string MeetingRemark { get; set; }
        public DevelopTask Development { get; set; }
        public DevelopTask SecurityTest { get; set; }
        public DevelopTask CodeReview { get; set; }
        public DevelopTask UAT { get; set; }
        public DevelopTask Deployment {get;set;}
        public ActionRole CloseProjectBy { get; set; }
        public RequestStatus Status { get; set; }

        public Request(
            string docNo,
            string title,
            string description,
            ActionRole requestBy)
        {
            DocNo = docNo;
            Title = title;
            Description = description;
            RequestBy = requestBy;
        }

        public void Approve(string approvedBy)
        {
            ApproveBy = new ActionRole();
            ApproveBy.ActionBy = approvedBy;
            ApproveBy.ActionDate = DateTime.Now;
            Status = RequestStatus.Approved;
        }
    }
}

ViewModels/RequestViewModel.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using dz.SoftwareRequest.Models;

namespace  dz.SoftwareRequest.ViewModels
{
    public class RequestViewModel
    {
        public int Id { get; set; }
        [Required]
        [DisplayName("Document No")]
        public string DocNo { get; set; }
        public string RequestBy { get; set; }
        [Required]
        [DisplayName("Title")]
        public string Title { get; set; }
        [Required]
        [DisplayName("Decription")]
        public string Description { get; set; }
        public DateTime? RequestDate { get; set; }
        public string ApprovedBy { get; set; }
        public DateTime? ApprovedDate {get;set;}
        public DevelopTask Development {get;set;}
        public DevelopTask CodeReview { get; set; }
        public DevelopTask Security { get; set; }
        public DevelopTask UAT { get; set; }
        public RequestStatus Status { get; set; } = RequestStatus.New;
    }
}

Controllers/DevelopController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using dz.SoftwareRequest.Data;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System;

namespace dz.SoftwareRequest.Controllers
{
    public class DevelopController:Controller
    {
        private readonly ApplicationContext _db;
        public DevelopController(ApplicationContext db)
        {
            _db = db;
        }
        public IActionResult Update(int Id)
        {
            var model = _db.Requests.FirstOrDefault(r=> r.Id == Id);
            
            return View(model);
        }
    }
}

Controllers/RequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using dz.SoftwareRequest.ViewModels;
using Microsoft.AspNetCore.Mvc;
using dz.SoftwareRequest.Models;
using static Microsoft.AspNetCore.Hosting.Internal.HostingApplication;
using dz.SoftwareRequest.Data;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace dz.SoftwareRequest.Controllers
{
    public class RequestController:Controller
    {
        private readonly ApplicationContext _db;
        public  RequestController(ApplicationContext db)
        {
            _db = db;
        }
        public async Task<IActionResult> Index()
        {
            var requests = await GetAllRequestAsync();

            var model =  requests.Select(r=> new RequestViewModel{
                Id = r.Id,
                DocNo = r.DocNo,
                Title = r.Title,
                Description = r.Description,
                RequestBy = r.RequestBy.ActionBy
            });

            return View(model);;
        }

        private async Task<IEnumerable<Request>> GetAllRequestAsync()
        {
            return await _db.Requests
                        .Include("RequestBy")
                        .Include("ApproveBy")
                        .ToListAsync();
        }

        private string GetNextDocNo()
        {
            var request = _db.Requests.OrderByDescending(r=> r.Id).FirstOrDefault();
            string prefix = request.DocNo.Substring(0,5);
            int no = int.Parse(request.DocNo.Substring(5,4));
            return prefix+(no+1).ToString("0000");
        }

        private Request GetRequestById(int id)
        {
            var request = _db.Requests
                      .Include("RequestBy")
                      .Include("ApproveBy")
                      .FirstOrDefault(r=> r.Id == id);
            return request;
        }

        [HttpGet]
        public IActionResult Create()
        {
            var model = new RequestViewModel();
            model.DocNo = GetNextDocNo();
            model.RequestDate = DateTime.Now;
            model.RequestBy = User.Identity.Name;

            return View(model);
        }
        
        [HttpPost]
        public IActionResult Create([Bind("DocNo,Title,Description,RequestBy")] RequestViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var request = new Request
                    (
                        model.DocNo,
                        model.Title,
                        model.Description,
                        new ActionRole
                        {
                            ActionBy = User.Identity.Name,
                            ActionDate =  DateTime.Now
                        }
                    );
                    CreateRequestAsync(request);
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateException e)
                {
                    ModelState.AddModelError("", e.Message);
                }
            }
            return View(model);
        }

        private async void CreateRequestAsync(Request request)
        {
            await _db.Requests.AddAsync(request);
            await _db.SaveChangesAsync();
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            var request = GetRequestById(id);

            var model = new RequestViewModel
            {
                Id = request.Id,
                DocNo = request.DocNo,
                RequestBy = request.RequestBy.ActionBy,
                RequestDate = request.RequestBy.ActionDate,
                Title = request.Title,
                Description = request.Description,
                ApprovedBy = request.ApproveBy != null ? request.ApproveBy.ActionBy : ""
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult Update(int id,[Bind("Id,DocNo,Title,Description")] RequestViewModel model)
        {        
            var request = GetRequestById(id);
            if (request == null)
                return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                   request.Title = model.Title;
                   request.Description = model.Description;      
                   _db.Update(request);
                   _db.SaveChanges();

                   return RedirectToAction("Index","Request");

                }catch (DbUpdateException e)
                {
                    ModelState.AddModelError("",e.Message);
                }
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult Approve(int id)
        {
            var request = GetRequestById(id);
            var model = new RequestViewModel();
            model.Id = request.Id;
            model.DocNo = request.DocNo;
            model.Title = request.Title;
            model.Description = request.Description;
            model.RequestBy = request.RequestBy.ActionBy;
            model.RequestDate = request.RequestBy.ActionDate;
            model.ApprovedBy = request.ApproveBy != null ? request.ApproveBy.ActionBy : "";
            model.ApprovedDate = request.ApproveBy != null ? request.ApproveBy.ActionDate : DateTime.Now;

            return View(model);
        }

        [HttpPost]
        public IActionResult Approve(int id,RequestViewModel model)
        {
            try
            {
                var request = GetRequestById(id);
                request.Approve(User.Identity.Name);
                _db.Update(request);
                _db.SaveChanges();
            }
            catch (System.Exception e)
            {
                ModelState.AddModelError("",e.Message);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Request/Approve.cshtml
@using dz.SoftwareRequest.ViewModels;
@model RequestViewModel;
@{
    ViewData["Title"] = "Approve Request";
}

<h4>Approve - <span>@Model.Title</span></h4>
<hr/>
<form asp-action="Approve" method="post">
     <input type="submit" class="btn btn-primary" value="Approve"></input>
     <a asp-action="Reject" asp-controller="Request" class="btn btn-danger">Reject</a>
     <a asp-action="Index" asp-controller="Request" class="btn btn-default">Close</a>
    <hr/>
    @Html.Partial("_CreateOrUpdate")
</form>

Views/Request/Create.cshtml
@using dz.SoftwareRequest.ViewModels;
@model RequestViewModel;
@{
    ViewData["Title"] = "New Request";
}

<h4>New Request</h4>
<hr/>
<form asp-action="Create" method="post">
    <input type="submit" class="btn btn-primary" value="Save"/>
    <a asp-action="SendReqest" asp-controller="Request" class="btn btn-danger">Send Request</a>
    <hr/>
    @Html.Partial("_CreateOrUpdate")
</form>

Views/Request/Index.cshtml
@using dz.SoftwareRequest.ViewModels;
@model IEnumerable<RequestViewModel>;

@{
    ViewData["Title"] = "Request List";
}
<h4>Request List</h4>

<table class="table">
    <thhead>
        <tr>
            <th>@Html.DisplayNameFor(model=> model.DocNo)</th>
            <th>@Html.DisplayNameFor(model=> model.Title)</th>
            <th>@Html.DisplayNameFor(model=> model.Description)</th>
            <th>@Html.DisplayNameFor(model=> model.RequestBy)</th>
            <th>@Html.DisplayNameFor(model=> model.ApprovedBy)</th>
            <td>@Html.DisplayNameFor(model=> model.Status)</td>
    </thhead>
    <tbody>
        @foreach(var request in Model)
        {
            <tr>
                <td>@Html.DisplayFor(p => request.DocNo)</td>
                <td>@Html.DisplayFor(p => request.Title)</td>
                <td>@Html.DisplayFor(p => request.Description)</td>
                <td>@Html.DisplayFor(p => request.RequestBy)</td>
                <td>@Html.DisplayFor(p => request.ApprovedBy)</td>
                <td>@Html.DisplayFor(p => request.Status)</td>
                <td>
                    <a asp-action="Update" asp-route-id="@request.Id">Edit</a>
                    <a asp-action="Approve" asp-route-id="@request.Id">Approve</a>
                    <a asp-controller="Develop" asp-action="Update" asp-route-id="@request.Id">Develop</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Request/Update.cshtml
@model dz.SoftwareRequest.ViewModels.RequestViewModel;

@{
    ViewData["Title"]= "Edit Request";
}

<h4>Edit - <span>@Model.Title</span></h4>
<hr/>
<form asp-action="Update">
    <input type="submit" class="btn btn-primary" value="Save"/>
    <hr/>

    @Html.Partial("_CreateOrUpdate");
</form>

Views/Request/View.cshtml
@using dz.SoftwareRequest.RequestViewModel;
@model RequestViewModel;

@{
    ViewData["Title"] = "Request Info"
}

Views/Request/_CreateOrUpdate.cshtml
@using dz.SoftwareRequest.ViewModels;
@model RequestViewModel;

<div class="panel panel-success">
    <div class="panel-heading">Infomation</div>
    <div class="panel-body">
        <div class="form-horizontal">
            <input type="hidden" asp-for="Id"/>
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DocNo" class="col-md-2 control-label"></label>
                <div class="col-md-2">
                    <input asp-for="DocNo" readonly="readonly" class="form-control"/>
                </div> 
            </div>
            <div class="form-group">
                <label asp-for="Title" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Title" class="form-control"/>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="col-md-2 control-label"></label>
                <div class="col-md-10">
                    <textarea rows="6" asp-for="Description" class="form-control"></textarea>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="RequestBy" class="col-md-2 control-label"></label>
                <div class="col-md-4">
                    <p class="form-control-static">@Model.RequestBy @Model.RequestDate</p>
                </div>
                <label asp-for="ApprovedBy" class="col-md-2 control-label"></label>
                <div class="col-md-4">
                     <p class="form-control-static">@Model.ApprovedBy @Model.ApprovedDate</p>
                </div>
            </div>
        </div>
    </div>
</div>